Format date
mchandleraz/realworld-vue pull request #7
Opened 2017-05-06 20:48 UTC by michalzagrodzki

1. Import moment.js.
2. Create filter for parsing date.
3. Format date according to spec.

2017-05-07 14:44 UTC, Gash003 commented
It's very probable that date parsing filter will be used not only in the `PostPreview` component, but across entire application.
Therefore, I would consider to make `date` filter to be accessible globally for the project. 
What do you think about that @michalzagrodzki ?

2017-05-07 19:29 UTC, michalzagrodzki commented
@Gash003 That is a very good point. I made it as a proof of concept, to show how it works. Later on, when this PR will be accepted I will refactor it for a global filter.

2017-05-11 04:04 UTC, mchandleraz requested changes
Thank you to both of you for this. I'm new to Vue, but is there a pattern for global filters? I'd rather just see a global filter in this PR. No sense in merging this just to refactor it. If there's no common pattern or you need help, let me know- I've got a couple ideas kicking around already.

Thanks again Michal!

2017-05-11 05:01 UTC, michalzagrodzki commented
I will make an update for this PR with global filter and updated dependencies.

2017-05-11 20:24 UTC, michalzagrodzki commented
Updated PR according to request.
Date filter is moved to main.js and setup as global filter.

@mchandleraz this PR is ready for merging.

2017-05-11 21:52 UTC, mchandleraz approved these changes

2017-05-11 21:52 UTC, merged